DROP TABLE EVENTS;
CREATE TABLE EVENTS(
 BUSINESS_ID INT,
 EVENT_TYPE VARCHAR(20),
 OCCURENCES INT,
 PRIMARY KEY (BUSINESS_ID, EVENT_TYPE)
);
INSERT INTO EVENTS VALUES (1, 'reviews', 7);
INSERT INTO EVENTS VALUES (3, 'reviews', 3);
INSERT INTO EVENTS VALUES (1, 'ads', 11);
INSERT INTO EVENTS VALUES (2, 'ads', 7);
INSERT INTO EVENTS VALUES (3, 'ads', 6);
INSERT INTO EVENTS VALUES (1, 'page views', 3);
INSERT INTO EVENTS VALUES (2, 'page views', 12);
COMMIT;