DROP TABLE QUEUE;
CREATE TABLE QUEUE(
 PERSON_ID INT,
 PERSON_NAME VARCHAR(30),
 WEIGHT INT,
 TURN INT,
 PRIMARY KEY (PERSON_ID)
);
INSERT INTO QUEUE VALUES (5, 'George Washington', 250, 1);
INSERT INTO QUEUE VALUES (3, 'John Adams', 350, 2);
INSERT INTO QUEUE VALUES (6, 'Thomas Jefferson', 400, 3);
INSERT INTO QUEUE VALUES (2, 'Will Johnliams', 200, 4);
INSERT INTO QUEUE VALUES (4, 'Thomas Jefferson', 175, 5);
INSERT INTO QUEUE VALUES (1, 'James Elephant', 500, 6);
COMMIT;