DROP TABLE FRIENDSHIP;
CREATE TABLE FRIENDSHIP(
 USER1_ID INT,
 USER2_ID INT,
 PRIMARY KEY (USER1_ID, USER2_ID)
);
DROP TABLE Likes;
CREATE TABLE Likes(
 user_id int,
 page_id int,
 PRIMARY KEY (user_id, page_id)
); 
INSERT INTO FRIENDSHIP VALUES (1, 2);
INSERT INTO FRIENDSHIP VALUES (1, 3);
INSERT INTO FRIENDSHIP VALUES (1, 4);
INSERT INTO FRIENDSHIP VALUES (2, 3);
INSERT INTO FRIENDSHIP VALUES (2, 4);
INSERT INTO FRIENDSHIP VALUES (2, 5);
INSERT INTO FRIENDSHIP VALUES (6, 1);
INSERT INTO LIKES VALUES (1, 88);
INSERT INTO LIKES VALUES (2, 23);
INSERT INTO LIKES VALUES (3, 24);
INSERT INTO LIKES VALUES (4, 56);
INSERT INTO LIKES VALUES (5, 11);
INSERT INTO LIKES VALUES (6, 33);
INSERT INTO LIKES VALUES (2, 77);
INSERT INTO LIKES VALUES (3, 77);
INSERT INTO LIKES VALUES (6, 88);
COMMIT;