DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES(
 EMPLOYEE_ID INT,
 EMPLOYEE_NAME VARCHAR(20),
 MANAGER_ID INT,
 PRIMARY KEY (EMPLOYEE_ID)
);
INSERT INTO EMPLOYEES VALUES (1, 'Boss', 1);
INSERT INTO EMPLOYEES VALUES (3, 'Alice', 3);
INSERT INTO EMPLOYEES VALUES (2, 'Bob', 1);
INSERT INTO EMPLOYEES VALUES (4, 'Daniel', 2);
INSERT INTO EMPLOYEES VALUES (7, 'Luis', 4);
INSERT INTO EMPLOYEES VALUES (8, 'Jhon', 3);
INSERT INTO EMPLOYEES VALUES (9, 'Angela', 8);
INSERT INTO EMPLOYEES VALUES (77, 'Robert', 1);
COMMIT;