DROP TABLE LOGS;
CREATE TABLE LOGS(
 LOG_ID INT,
 PRIMARY KEY (LOG_ID)
);
INSERT INTO LOGS VALUES (1);
INSERT INTO LOGS VALUES (2);
INSERT INTO LOGS VALUES (3);
INSERT INTO LOGS VALUES (7);
INSERT INTO LOGS VALUES (8);
INSERT INTO LOGS VALUES (10);
COMMIT;