DROP TABLE STOCKS;
CREATE TABLE STOCKS(
 STOCK_NAME VARCHAR(30),
 -- MySQL
 -- operation enum('Sell', 'Buy'),
 OPERATION VARCHAR(10) CHECK(OPERATION IN ('Sell', 'Buy')),
 OPERATION_DAY INT,
 PRICE INT,
 PRIMARY KEY (STOCK_NAME, OPERATION_DAY)
);
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Leetcode', 'Buy', '1', '1000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Buy', '2', '10');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Leetcode', 'Sell', '5', '9000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Handbags', 'Buy', '17', '30000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Sell', '3', '1010');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Buy', '4', '1000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Sell', '5', '500');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Buy', '6', '1000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Handbags', 'Sell', '29', '7000');
INSERT INTO STOCKS (STOCK_NAME, OPERATION, OPERATION_DAY, PRICE) VALUES ('Corona Masks', 'Sell', '10', '10000');
COMMIT;