DROP TABLE VARIABLES;
CREATE TABLE VARIABLES(
 NAME VARCHAR(1),
 VALUE INT,
 PRIMARY KEY (NAME)
);
DROP TABLE EXPRESSIONS;
CREATE TABLE EXPRESSIONS(
 LEFT_OPERAND VARCHAR(1),
 -- MySQL
 -- operator enum('<', '>', '='),
 OPERATOR VARCHAR(1) CHECK( OPERATOR IN ('<', '>', '=') ),  
 RIGHT_OPERAND VARCHAR(1),
 PRIMARY KEY (LEFT_OPERAND, OPERATOR, RIGHT_OPERAND)
);
INSERT INTO VARIABLES VALUES ('x', 66);
INSERT INTO VARIABLES VALUES ('y', 77);
INSERT INTO EXPRESSIONS VALUES ('x','>','y');
INSERT INTO EXPRESSIONS VALUES ('x','<','y');
INSERT INTO EXPRESSIONS VALUES ('x','=','y');
INSERT INTO EXPRESSIONS VALUES ('y','>','x');
INSERT INTO EXPRESSIONS VALUES ('y','<','x');
INSERT INTO EXPRESSIONS VALUES ('x','=','x');
COMMIT;