DROP TABLE SALARIES;
CREATE TABLE SALARIES(
 COMPANY_ID INT,
 EMPLOYEE_ID INT,
 EMPLOYEE_NAME VARCHAR(30),
 SALARY INT,
 PRIMARY KEY (COMPANY_ID, EMPLOYEE_ID)
);
INSERT INTO SALARIES VALUES (1, 1, 'Tony', 2000);
INSERT INTO SALARIES VALUES (1, 2, 'Pronub', 21300);
INSERT INTO SALARIES VALUES (1, 3, 'Tyrrox', 10800);
INSERT INTO SALARIES VALUES (2, 1, 'Pam', 300);
INSERT INTO SALARIES VALUES (2, 7, 'Bassem', 450);
INSERT INTO SALARIES VALUES (2, 9, 'Hermione', 700);
INSERT INTO SALARIES VALUES (3, 7, 'Bocaben', 100);
INSERT INTO SALARIES VALUES (3, 2, 'Ognjen', 2200);
INSERT INTO SALARIES VALUES (3, 13, 'Nyancat', 3300);
INSERT INTO SALARIES VALUES (3, 15, 'Morninngcat', 7777);
COMMIT;