-- 550. Managers With At Least 5 Direct Reports
-- Write a SQL query that finds out managers with at least 5 direct report.

-- Create table
DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(
 ID INT,
 NAME VARCHAR(20),
 DEPARTMENT CHAR(1),
 MANAGERID INT,
 PRIMARY KEY (ID)
);

INSERT INTO EMPLOYEE VALUES (101, 'John', 'A', null);
INSERT INTO EMPLOYEE VALUES (102, 'Dan', 'A', 101);
INSERT INTO EMPLOYEE VALUES (103, 'James', 'A', 101);
INSERT INTO EMPLOYEE VALUES (104, 'Amy', 'A', 101);
INSERT INTO EMPLOYEE VALUES (105, 'Anne', 'A', 101);
INSERT INTO EMPLOYEE VALUES (106, 'Ron', 'B', 101);
COMMIT;

-- Solution
SELECT E1.NAME
FROM EMPLOYEE E1
WHERE E1.ID = (
	SELECT E2.MANAGERID
    FROM EMPLOYEE E1, EMPLOYEE E2
    WHERE E1.ID = E2.MANAGERID
    GROUP BY E2.MANAGERID
    HAVING COUNT(E2.ID));
    



