DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(
 ID INT,
 NAME VARCHAR(20),
 DEPARTMENT CHAR(1),
 MANAGERID INT,
 PRIMARY KEY (ID)
);

INSERT INTO EMPLOYEE VALUES (101, 'John', 'A', null);
INSERT INTO EMPLOYEE VALUES (102, 'Dan', 'A', 101);
INSERT INTO EMPLOYEE VALUES (103, 'James', 'A', 101);
INSERT INTO EMPLOYEE VALUES (104, 'Amy', 'A', 101);
INSERT INTO EMPLOYEE VALUES (105, 'Anne', 'A', 101);
INSERT INTO EMPLOYEE VALUES (106, 'Ron', 'B', 101);
COMMIT;