DROP TABLE STUDENT;
CREATE TABLE STUDENT( 
 STUDENT_ID INT,
 STUDENT_NAME VARCHAR(10),
 GENDER CHAR(1),
 DEPT_ID INT,
 PRIMARY KEY (STUDENT_ID)
);

DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT( 
 DEPT_ID INT,
 DEPT_NAME VARCHAR(20),
 PRIMARY KEY (DEPT_ID)
);

INSERT INTO STUDENT VALUES (1, 'Jack', 'M', 1);
INSERT INTO STUDENT VALUES (2, 'Jane', 'F', 1);
INSERT INTO STUDENT VALUES (3, 'Mark', 'M', 2);

INSERT INTO DEPARTMENT VALUES (1, 'Engineering');
INSERT INTO DEPARTMENT VALUES (2, 'Science');
INSERT INTO DEPARTMENT VALUES (3, 'Law');
COMMIT;