DROP TABLE TREE;
CREATE TABLE TREE(
 ID INT,
 P_ID INT,
 PRIMARY KEY (ID)
);

INSERT INTO TREE VALUES (1, null);
INSERT INTO TREE VALUES (2, 1);
INSERT INTO TREE VALUES (3, 1);
INSERT INTO TREE VALUES (4, 2);
INSERT INTO TREE VALUES (5, 2);
COMMIT;