-- 1050. Actors and Directors Who Cooperated At Least Three Times
-- Write a SQL query for a report that provides the pairs (actor_id, director_id) where the actor have cooperated with the director at least 3 times.

-- Create table
DROP TABLE ACTORDIRECTOR;
CREATE TABLE ACTORDIRECTOR
(
 ACTOR_ID INT,
 DIRECTOR_ID INT,
 TIMESTAMP INT,
 PRIMARY KEY (TIMESTAMP)
);
 
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 0);
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 1);
INSERT INTO ACTORDIRECTOR VALUES (1, 1, 2);
INSERT INTO ACTORDIRECTOR VALUES (1, 2, 3);
INSERT INTO ACTORDIRECTOR VALUES (1, 2, 4);
INSERT INTO ACTORDIRECTOR VALUES (2, 1, 5);
INSERT INTO ACTORDIRECTOR VALUES (2, 1, 6);
COMMIT;

-- Solution
SELECT A.ACTOR_ID, A.DIRECTOR_ID
FROM ACTORDIRECTOR A
GROUP BY A.ACTOR_ID
HAVING COUNT(DIRECTOR_ID) >= 3;

