-- 1068. Product Sales Analysis I
-- Write an SQL query that reports all product names of the products in the Sales table along with their selling year and price.

-- Create table
DROP TABLE SALES;
DROP TABLE PRODUCT;
CREATE TABLE SALES
(SALE_ID INT,
 PRODUCT_ID INT,
 YEAR INT,
 QUANTITY INT,
 PRICE INT,
 PRIMARY KEY (SALE_ID, YEAR));
 
CREATE TABLE PRODUCT
(PRODUCT_ID INT,
 PRODUCT_NAME VARCHAR(20));
 
INSERT INTO SALES VALUES (1, 100, 2008, 10, 5000);
INSERT INTO SALES VALUES (2, 100, 2009, 12, 5000);
INSERT INTO SALES VALUES (7, 200, 2011, 15, 9000);

INSERT INTO PRODUCT VALUES (100, 'Nokia');
INSERT INTO PRODUCT VALUES (200, 'Apple');
INSERT INTO PRODUCT VALUES (300, 'Samsung');
COMMIT;

-- Solution
SELECT P.PRODUCT_NAME, S.`YEAR`, S.PRICE
FROM PRODUCT P, SALES S 
WHERE P.PRODUCT_ID = S.PRODUCT_ID;

