DROP TABLE DEPARTMENTS;
CREATE TABLE DEPARTMENTS(
 ID INT,
 NAME VARCHAR(50),
 PRIMARY KEY (ID)
);
 
DROP TABLE STUDENTS;
CREATE TABLE STUDENTS(
 ID INT,
 NAME VARCHAR(20),
 DEPARTMENT_ID INT,
 PRIMARY KEY (ID)
);

INSERT INTO DEPARTMENTS VALUES (1, 'Electrical Engineering');
INSERT INTO DEPARTMENTS VALUES (7, 'Computer Engineering');
INSERT INTO DEPARTMENTS VALUES (13, 'Bussiness Administration');
INSERT INTO STUDENTS VALUES (23, 'Alice', 1);
INSERT INTO STUDENTS VALUES (1, 'Bob', 7);
INSERT INTO STUDENTS VALUES (5, 'Jennifer', 13);
INSERT INTO STUDENTS VALUES (2, 'John', 14);
INSERT INTO STUDENTS VALUES (4, 'Jasmine', 77);
INSERT INTO STUDENTS VALUES (3, 'Steve' , 74);
INSERT INTO STUDENTS VALUES (6, 'Luis', 1);
INSERT INTO STUDENTS VALUES (8, 'Jonathan', 7);
INSERT INTO STUDENTS VALUES (7, 'Daiana', 33);
INSERT INTO STUDENTS VALUES (11, 'Madelynn' , 1);
COMMIT;